### ISSUE TITLE
Focus contrast in insufficient in dropdown menu immediately following username

### ISSUE THREAD

**Issue by lee0c** [hometown-fork/hometown#1374]
### Steps to reproduce the problem

1. Using tab navigation, move to the dropdown menu following username + edit profile link
2. Activate the dropdown and begin to move through it
3. Notice that there is no focus outline, and the contrast between focused and unfocused states is low (1.72:1)

### Expected behaviour

Higher contrast/more visible focus for dropdown menu items

### Actual behaviour

Low contrast

### Mastodon instance

flipping.rocks

### Mastodon version

v4.2.17+hometown-1.1.2

### Browser name and version

Firefox 145.0.2

### Operating system

Win11

**Comment by lee0c** [comment]
Fixed in mainline masto (removed dropdown)

**Comment by nachtjasmin** [comment]
I think it's still present in `v4.5.11+hometown-1.2.1`. There's no focus outline around the search bar at all. Not sure whether it's Hometown-specific or also present in Mastodon 4.5.11 itself, due to a lack of a test instance right now.

**Comment by lee0c** [comment]
@nachtjasmin This issue referred to the dropdown following the username (now removed) - but I can check the search bar in mainline masto. I believe it has good contrast there.

**Comment by lee0c** [comment]
Yes, the search bar experience in mainline masto (tested against v4.6.0) is excellent
